[package]
name = "matchdrop"
version = "0.1.0"
edition = "2021"
authors = ["Lark <lark@lark.gay>"]

  [package.metadata.release]
  release = false

  # https://github.com/rustwasm/wasm-pack/issues/1247
  [package.metadata.wasm-pack.profile.release]
  wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.4.2", features = ["http", "axum"] }
worker-macros = { version = "0.4.2", features = ["http"] }
axum = { version = "0.7", default-features = false, features = [
  "json",
  "macros",
] }
tower-service = "0.3.2"
console_error_panic_hook = { version = "0.1.1" }
tower-http = { version = "0.6.2", features = [
  "trace",
  "cors",
  "auth",
  "sensitive-headers",
] }
serde = { version = "1.0.215", features = ["derive"] }
secrecy = { version = "0.10.3", features = ["serde"] }
futures = "0.3.31"
constant_time_eq = "0.3.1"
rand = "0.8.5"
