name = "matchdrop"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-22"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "matchdrop"
database_id = "be75842d-ef1d-4602-a6c9-3d6d30315d66"
preview_database_id = "4895dbd4-f3c5-4fc5-9015-61384c4510de"

[env.dev]

  [[env.dev.d1_databases]]
  binding = "DB"
  database_name = "matchdrop-dev"
  database_id = "4895dbd4-f3c5-4fc5-9015-61384c4510de"
